<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\RF4Overlay.Core\RF4Overlay.Core.csproj" />
    <ProjectReference Include="..\RF4Overlay.Features\RF4Overlay.Features.csproj" />
    <ProjectReference Include="..\RF4Overlay.Infrastructure\RF4Overlay.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
